### ISSUE TITLE
スニペットをメディアwiki記法から通常の記法にする

### ISSUE THREAD

**Issue by yegusa** [masao/irce-wikipedia#34]
スニペットをメディアwiki記法から通常の記法にする

![image](https://cloud.githubusercontent.com/assets/1328499/5890052/c7eaf1e6-a48a-11e4-80c7-392345939dc8.png)

**Comment by masao** [comment]
だいたいできたので、クローズ。
![image](https://cloud.githubusercontent.com/assets/38825/6772390/12377f4e-d140-11e4-91fc-8c476e0c6a99.png)
