### ISSUE TITLE
画像が複数あるページのときに、一部画像が取り込めてない場合がある

### ISSUE THREAD

**Issue by yegusa** [masao/irce-wikipedia#37]
「コスモス」を例に。
-----
修正前：
![image](https://cloud.githubusercontent.com/assets/1328499/5890079/89769008-a48c-11e4-83d9-c64abaf73298.png)

----
wikipedia オリジナル：
![image](https://cloud.githubusercontent.com/assets/1328499/5890086/c122551e-a48c-11e4-963b-42335096090b.png)

**Comment by masao** [comment]
2015-04-26時点：ラジアンス等は画像表示されるようになった！
しかし、[水管橋とコスモス（群生）](http://ja.wikipedia.org/wiki//%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB:Konosu_Ara_River_Aqueduct_3.JPG)が表示されなくなった。。。
